// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7axvyjHatIF94cILeGTbRNlyTxWhKek',
    appId: '1:854907181721:web:0b93bd9c60da086892b608',
    messagingSenderId: '854907181721',
    projectId: 'appmovilcrespf',
    authDomain: 'appmovilcrespf.firebaseapp.com',
    storageBucket: 'appmovilcrespf.firebasestorage.app',
    measurementId: 'G-Q3R7KKV3XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzSYaMWwRF0lxkfd-mc5SylEXh51vLHc',
    appId: '1:854907181721:android:5db4b5074f74260b92b608',
    messagingSenderId: '854907181721',
    projectId: 'appmovilcrespf',
    storageBucket: 'appmovilcrespf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xT053qq1e3LULiW8ehuNBVkEtNKFH8k',
    appId: '1:854907181721:ios:15311bad94cfc0d492b608',
    messagingSenderId: '854907181721',
    projectId: 'appmovilcrespf',
    storageBucket: 'appmovilcrespf.firebasestorage.app',
    iosBundleId: 'com.example.appCrespf',
  );
}
